# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
### dependencie for /module/yacl/
  - package-ecosystem: gomod
    directory: /module/yacl/
    schedule:
       interval: daily
    assignees:
       - swaros
### dependencie for /module/yamc/
  - package-ecosystem: gomod
    directory: /module/yamc/
    schedule:
       interval: daily
    assignees:
       - swaros
### dependencie for /module/runner/
  - package-ecosystem: gomod
    directory: /module/runner/
    schedule:
       interval: daily
    assignees:
       - swaros
### dependencie for /module/configure/
  - package-ecosystem: gomod
    directory: /module/configure/
    schedule:
       interval: daily
    assignees:
       - swaros
### dependencie for /module/dirhandle/
  - package-ecosystem: gomod
    directory: /module/dirhandle/
    schedule:
       interval: daily
    assignees:
       - swaros
### dependencie for /module/systools/
  - package-ecosystem: gomod
    directory: /module/systools/
    schedule:
       interval: daily
    assignees:
       - swaros
### dependencie for /module/trigger/
  - package-ecosystem: gomod
    directory: /module/trigger/
    schedule:
       interval: daily
    assignees:
       - swaros
### dependencie for /module/linehack/
  - package-ecosystem: gomod
    directory: /module/linehack/
    schedule:
       interval: daily
    assignees:
       - swaros
### dependencie for /module/ctemplate/
  - package-ecosystem: gomod
    directory: /module/ctemplate/
    schedule:
       interval: daily
    assignees:
       - swaros
### dependencie for /module/ctxout/
  - package-ecosystem: gomod
    directory: /module/ctxout/
    schedule:
       interval: daily
    assignees:
       - swaros
### dependencie for /module/taskrun/
  - package-ecosystem: gomod
    directory: /module/taskrun/
    schedule:
       interval: daily
    assignees:
       - swaros
### dependencie for /module/awaitgroup/
  - package-ecosystem: gomod
    directory: /module/awaitgroup/
    schedule:
       interval: daily
    assignees:
       - swaros
### dependencie for /module/shellcmd/
  - package-ecosystem: gomod
    directory: /module/shellcmd/
    schedule:
       interval: daily
    assignees:
       - swaros
### dependencie for /module/tasks/
  - package-ecosystem: gomod
    directory: /module/tasks/
    schedule:
       interval: daily
    assignees:
       - swaros