task:
  - id: go-check
    require:
      system: linux
    script:
      - echo ${GOROOT}
      - go env | grep GOROOT
      - go env | grep GOVERSION
      - go version 
 
  - id: go-check
    require:
      system: windows
    script:
      - echo ${GOROOT}
      - go env | Select-String GOROOT
      - go env | Select-String GOVERSION
      - go version

  - id: test
    script:
      - go clean -testcache ./..
      - go test -cover -v -failfast ./...

  - id: test-each
    options:
      displaycmd: true
    script:
      - go test -failfast -timeout 30s -v github.com/swaros/contxt/context/systools
      - go test -failfast -timeout 30s -v github.com/swaros/contxt/context/output
      - go test -failfast -timeout 60s -v github.com/swaros/contxt/context/cmdhandle
      - go test -failfast -timeout 30s -v github.com/swaros/contxt/context/configure
      - go test -failfast -timeout 60s -v github.com/swaros/contxt/context/dirhandle

  - id: set-version
    options:
      displaycmd: true
      invisible: true
    variables:
      bin-out: contxt
    require:
      system: linux
    script:
      - "#@var main-version cat docs/mainversion"
      - "#@var mid-version cat docs/midversion"
      - "#@var minor-version cat docs/minversion"
      - "#@var build-hash date -u +.%Y%m%d.%H%M%S"
      - "#@set bin-out contxt"

  - id: set-version
    options:
      displaycmd: true
      invisible: true
      maincmd: pwsh
      mainparams:
        - "-Command"
    require:
      system: windows
    script:
      - "#@var main-version type docs/mainversion"
      - "#@var mid-version type docs/midversion"
      - "#@var minor-version type docs/minversion"
      - "#@set build-hash windows"
      - "#@set bin-out contxt.exe"

  - id: set-version
    options:
      displaycmd: true
      invisible: true
    script:
     - echo "version ${main-version}.${mid-version}.${minor-version} ${build-hash} out ${bin-out}"

  - id: build
    needs:
      - set-version
    next:
      - build-exec

  - id: build-exec
    options:
      displaycmd: true
      invisible: true
    require:
      variables:
        main-version: "*"
        mid-version: "*"
        minor-version: "*"
        bin-out: "*"
    next:
      - verify-build
    script:
      - echo "build start"
      - go build -ldflags "-X github.com/swaros/contxt/context/configure.minversion=${minor-version} -X github.com/swaros/contxt/context/configure.midversion=${mid-version} -X github.com/swaros/contxt/context/configure.mainversion=${main-version} -X github.com/swaros/contxt/context/configure.build=${build-hash}" -o ./bin/${bin-out} cmd/cmd-contxt/main.go

  - id: verify-build
    options:
      displaycmd: true
      invisible: true
    require:
      exists:
        - bin/${bin-out}
    script:
       - bin/${bin-out} version

