--- 
task: 
  - id: build
    script: 
      - rm -rf dist/
      - goreleaser build --skip-validate --rm-dist
      - cd dist/contxt_linux_amd64 && ./contxt version
  
  - id: release
    script:
      - goreleaser release --skip-validate --rm-dist --release-notes=./docs/CHANGELOG.md

  - id: init
    script: 
      - "git status"
