version: "0.2.2"
task:
  - id: go-check
    require:
      system: linux
    script:
      - echo ${GOROOT}
      - go env | grep GOROOT
      - go env | grep GOVERSION
      - go version 
 
  - id: go-check
    require:
      system: windows
    script:
      - echo ${GOROOT}
      - go env | Select-String GOROOT
      - go env | Select-String GOVERSION
      - go version

  - id: dos2unix
    require:
      system: linux
    script:
      - find . -type f -print0 | xargs -0 dos2unix

  - id: cleanup-dependencies
    script:      
    {{- range $k, $test := $.module }}    
      - | 
       cd {{ $test.modul }}
       go mod tidy
       
    {{- end }}
      - git status
      
  - id: test
    script:
    {{- range $k, $test := $.module }}
      #- go clean -testcache ./{{ $test.modul }}/./...
      - go test -cover -v -failfast ./{{ $test.modul }}/./...
    {{- end }}

  - id: test-each
    needs:
      - test-sys
      - test-conf
      - test-cmd
      - test-dir

  - id: test-sys
    options:
      displaycmd: true
    script:
      - go test -failfast -timeout 300s -v ./module/systools/./...      

  - id: test-conf
    options:
      displaycmd: true
    script:      
      - go test -failfast -timeout 300s -v ./module/configure/./...
  
  - id: test-cmd
    options:
      displaycmd: true
      stickcursor: false
    script:      
      - go test -failfast -timeout 300s -v ./module/taskrun/./...

  - id: test-dir
    options:
      displaycmd: true
    script:      
      - go test -failfast -timeout 300s -v ./module/dirhandle/./...

  - id: set-version
    options:
      displaycmd: false
      invisible: true
    variables:
      bin-out: contxt
    require:
      system: linux
    script:
      - "#@var main-version cat docs/mainversion"
      - "#@var mid-version cat docs/midversion"
      - "#@var minor-version cat docs/minversion"
      - "#@var build-hash date -u +.%Y%m%d.%H%M%S"
      - "#@set bin-out contxt"

  - id: set-version
    options:
      displaycmd: false
      invisible: true
      maincmd: pwsh
      mainparams:
        - "-Command"
    require:
      system: windows
    script:
      - "#@var main-version type docs/mainversion"
      - "#@var mid-version type docs/midversion"
      - "#@var minor-version type docs/minversion"
      - "#@var build-hash Get-Date -UFormat \"%m.%d.%Y.%R\""
      - "#@set bin-out contxt.exe"

  - id: set-version
    options:
      displaycmd: false
      invisible: true
    script:
     - echo "version ${main-version}.${mid-version}.${minor-version} ${build-hash} out ${bin-out}"

  - id: build
    needs:
      - set-version
    next:
      - build-exec

  - id: build-exec
    options:
      displaycmd: false
      invisible: true
    require:
      variables:
        main-version: "*"
        mid-version: "*"
        minor-version: "*"
        bin-out: "*"
    next:
      - verify-build
    script:
      - echo "build start----"
      - echo "   target -- ${bin-out}"
      - go build -ldflags "-X github.com/swaros/contxt/configure.minversion=${minor-version} -X github.com/swaros/contxt/configure.midversion=${mid-version} -X github.com/swaros/contxt/configure.mainversion=${main-version} -X github.com/swaros/contxt/configure.build=${build-hash}" -o ./bin/${bin-out} cmd/cmd-contxt/main.go
      - echo "   done   -- build "

  - id: verify-build
    options:
      displaycmd: false
      invisible: true
    require:
      exists:
        - bin/${bin-out}
    script:
       - echo "verifiy build version"
       - bin/${bin-out} version

## install local. this is used by the Makefile
## because contxt can not update himself while it is running,
## or is just not installed yet
## so make runs the new builded contxt binary

  - id: install-local
    variables:
      local-install: "yes"
    needs:
      - build
    next:
      - install-local-bin

## check for ~/bin 
  - id: install-local-bin
    script:
      - echo "try the ${HOME}/bin usage"

## success for local bin/ 
  - id: install-local-bin 
    options:
      displaycmd: true
    require:
      exists:
        - ${HOME}/bin
      system: linux
      variables:
        local-install: "=yes"
        bin-out: "*"
    script:
      - echo "we will use /bin/${bin-out}"
      - yes | cp -i bin/${bin-out} $HOME/bin/${bin-out} # # to solve the cp -i alias issue
      - echo "check versions"
      - contxt version
      


## fail for local bin/
  - id: install-local-bin
    options:
      displaycmd: true
    require:
      notExists:
        - ${HOME}/bin
      system: linux
      variables:
        local-install: "=yes"
        bin-out: "*"
    script:
      - echo "${HOME}/bin not exists. will not be used"
    next:
      - install-local-dot-bin
    

  - id: install-local-dot-bin
    script:
      - echo "try $HOME/.local/bin/"

  ## fail test .local/bin
  - id: install-local-dot-bin
    require:
      notExists:
        - ${HOME}/.local/bin/
      system: linux
      variables:
        local-install: "=yes"
        bin-out: "*"        
    script:
      - echo "no .local/bin dir"      
      
## if exists ...copy file
  - id: install-local-dot-bin
    require:
      exists:
        - ${HOME}/.local/bin/
      system: linux
      variables:
        local-install: "=yes"
        bin-out: "*"        
    script:
      - echo "using ~/.local/bin/ to copy ${bin-out}"
      - yes | cp -i bin/${bin-out} $HOME/.local/bin/${bin-out}  # to solve the cp -i alias issue
      - echo "check versions"
      - contxt version

## tview test app #####
  - id: tview-build
    require:
      system: linux
    script:
      - echo "build tview for linux"
      - go build -o ./bin/tview-example cmd/cmd-tview/main.go
  
  - id: tview-build
    require:
      system: windows
    script:
      - echo "build tview for windows"
      - go build -o ./bin/tview-example.exe cmd/cmd-tview/main.go

  - id: tview-build
    require:
      system: linux
      exists:
        - bin/tview-example
    script:
      - chmod 755 bin/tview-example
      - echo "if not executed try to start the application with"
      - echo "./bin/tview-example"
      

  - id: tview-run
    needs:
      - tview-build

  - id: tview-run
    require:
      system: linux
      exists:
        - bin/tview-example
    script:
      - ./bin/tview-example        
  
  - id: tview-run
    require:
      system: windows
      exists:
        - bin/tview-example.exe
    script:
      - ./bin/tview-example.exe        
  