version: "0.2.2"
task:
  - id: go-check
    require:
      system: linux
    script:
      - echo ${GOROOT}
      - go env | grep GOROOT
      - go env | grep GOVERSION
      - go version 
 
  - id: go-check
    require:
      system: windows
    script:
      - echo ${GOROOT}
      - go env | Select-String GOROOT
      - go env | Select-String GOVERSION
      - go version

  - id: cleanup-dependencies
    script:
      - go mod tidy
      - git status
      
  - id: test
    script:
      - go clean -testcache ./..
      - go test -cover -v -failfast ./...

  - id: test-each
    needs:
      - test-sys
      - test-conf
      - test-cmd
      - test-dir

  - id: test-sys
    options:
      displaycmd: true
    script:
      - go test -failfast -timeout 30s -v github.com/swaros/contxt/context/systools

  - id: test-conf
    options:
      displaycmd: true
    script:
      - go test -failfast -timeout 30s -v github.com/swaros/contxt/context/configure
  
  - id: test-cmd
    options:
      displaycmd: true
      stickcursor: false
    script:
      - go test -failfast -timeout 300s -v github.com/swaros/contxt/context/cmdhandle

  - id: test-dir
    options:
      displaycmd: true
    script:
      - go test -failfast -timeout 20s -v github.com/swaros/contxt/context/dirhandle

  - id: set-version
    options:
      displaycmd: true
      invisible: true
    variables:
      bin-out: contxt
    require:
      system: linux
    script:
      - "#@var main-version cat docs/mainversion"
      - "#@var mid-version cat docs/midversion"
      - "#@var minor-version cat docs/minversion"
      - "#@var build-hash date -u +.%Y%m%d.%H%M%S"
      - "#@set bin-out contxt"

  - id: set-version
    options:
      displaycmd: true
      invisible: true
      maincmd: pwsh
      mainparams:
        - "-Command"
    require:
      system: windows
    script:
      - "#@var main-version type docs/mainversion"
      - "#@var mid-version type docs/midversion"
      - "#@var minor-version type docs/minversion"
      - "#@var build-hash Get-Date -UFormat \"%m.%d.%Y.%R\""
      - "#@set bin-out contxt.exe"

  - id: set-version
    options:
      displaycmd: true
      invisible: true
    script:
     - echo "version ${main-version}.${mid-version}.${minor-version} ${build-hash} out ${bin-out}"

  - id: build
    needs:
      - set-version
    next:
      - build-exec

  - id: build-exec
    options:
      displaycmd: true
      invisible: true
    require:
      variables:
        main-version: "*"
        mid-version: "*"
        minor-version: "*"
        bin-out: "*"
    next:
      - verify-build
    script:
      - echo "build start"
      - go build -ldflags "-X github.com/swaros/contxt/context/configure.minversion=${minor-version} -X github.com/swaros/contxt/context/configure.midversion=${mid-version} -X github.com/swaros/contxt/context/configure.mainversion=${main-version} -X github.com/swaros/contxt/context/configure.build=${build-hash}" -o ./bin/${bin-out} cmd/cmd-contxt/main.go

  - id: verify-build
    options:
      displaycmd: true
      invisible: true
    require:
      exists:
        - bin/${bin-out}
    script:
       - bin/${bin-out} version

  - id: install-local
    variables:
      local-install: "yes"
    needs:
      - build
    next:
      - install-local-bin
      - install-local-dot-bin

  - id: install-local-bin
    script:
      - echo "try the ${HOME}/bin usage"

  - id: install-local-bin
    options:
      displaycmd: true
    require:
      exists:
        - ${HOME}/bin
      system: linux
      variables:
        local-install: "=yes"
        bin-out: "*"
    script:
      - cp bin/${bin-out} $HOME/bin/${bin-out}


## fail for local bin/
  - id: install-local-bin
    options:
      displaycmd: true
    variables:
      local-install: "NO" # if we take care... no one else should too
    require:
      notExists:
        - ${HOME}/bin
      system: linux
      variables:
        local-install: "=yes"
        bin-out: "*"
    script:
      - echo "${HOME}/bin not exists. will not be used"

  - id: install-local-dot-bin
    

  ## fail test .local/bin
  - id: install-local-dot-bin
    require:
      notExists:
        - ${HOME}/.local/bin/
      system: linux
      variables:
        local-install: "=yes"
        bin-out: "*"        
    script:
      - echo "no .local/bin dir"      
      
## if exists ...copy file
  - id: install-local-dot-bin
    require:
      exists:
        - ${HOME}/.local/bin/
      system: linux
      variables:
        local-install: "=yes"
        bin-out: "*"        
    script:
      - echo "using ~/.local/bin/ to copy ${bin-out}"
      - cp bin/${bin-out} $HOME/.local/bin/${bin-out}
      - echo "check versions"
      - contxt version

    