# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      #- windows
      #- darwin
    main: ./cmd/cmd-contxt/main.go
    ldflags:
      - -X github.com/swaros/contxt/context/configure.minversion=`cat docs/minversion` -X github.com/swaros/contxt/context/configure.midversion=`cat docs/midversion` -X github.com/swaros/contxt/context/configure.mainversion=`cat docs/mainversion` -X github.com/swaros/contxt/context/configure.build=`date -u +.%Y%m%d.%H%M%S`" -i -o ./bin/contxt cmd/cmd-contxt/main.go
archives:
  - replacements:
      #darwin: Darwin
      linux: Linux
      #windows: Windows
      #386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

env_files:  
  github_token: ~/keystore/tokens/goreleaser.token
