module:
  -
    modul: yacl
    local: true
    test:
      timeout: 30s

  -
    modul: yamc
    local: true
    test:
      timeout: 30s

  -
    modul: configure
    local: true
    test:
      timeout: 30s

  -
    modul: dirhandle
    local: true
    test:
      timeout: 30s

  -
    modul: systools
    local: true
    test:
      timeout: 30s

  -
    modul: trigger
    version: "v0.4.0"
    local: true
    test:
      timeout: 30s

  -
    modul: linehack    
    local: true
    test:
      timeout: 30s

  -
    modul: ctxout
    local: true
    test:
      timeout: 30s

  -
    modul: taskrun
    local: true
    test:
      timeout: 60s

  -
    modul: awaitgroup
    local: true
    version: "v0.4.0"
    test:
      timeout: 30s

  -
    modul: shellcmd
    local: true
    test:
      timeout: 30s

  -
    modul: tasks
    local: true
    test:
      timeout: 30s

  -
    modul: manout
    local: false
    path: ${WS0_manout_root}

  -
    modul: outinject
    local: false
    path: ${WS0_outinject_root}
