module:
  - 
    modul: configure
    test:
      timeout: 30s

  - 
    modul: dirhandle
    test:
      timeout: 30s

  - 
    modul: systools
    test:
      timeout: 30s

  - 
    modul: trigger
    test:
      timeout: 30s

  - 
    modul: taskrun
    test:
      timeout: 30s
      
  - 
    modul: awaitgroup
    test:
      timeout: 30s
  