module:
  -
    modul: configure
    local: true
    test:
      timeout: 30s

  -
    modul: dirhandle
    local: true
    test:
      timeout: 30s

  -
    modul: systools
    local: true
    test:
      timeout: 30s

  -
    modul: trigger
    local: true
    test:
      timeout: 30s

  -
    modul: taskrun
    local: true
    test:
      timeout: 60s

  -
    modul: awaitgroup
    local: true
    test:
      timeout: 30s

  -
    modul: shellcmd
    local: true
    test:
      timeout: 30s

  -
    modul: manout
    local: false
    path: ${WS0_manout_root}
