module:
  -
    modul: yacl
    clean:
      - "tmpfiles/*.yml"
    local: true
    test:
      timeout: 30s

  -
    modul: yamc
    local: true
    test:
      timeout: 30s

  -
    modul: runner
    local: true
    clean:
      - "testdata/*.log"
      - "testdata/projects01/*ctx_projects.yml"
    test:
      timeout: 30s

  -
    modul: ctxtcell
    local: true
    test:
      timeout: 20s

  -
    modul: configure
    local: true
    clean:
      - "test/temp/*.yml"
      - "test/temp/*.yaml"
      - "test/temp/*.json"
    test:
      timeout: 30s

  -
    modul: dirhandle
    local: true
    test:
      timeout: 30s

  -
    modul: systools
    local: true
    test:
      timeout: 30s

  -
    modul: trigger
    version: "v0.4.0"
    local: true
    test:
      timeout: 30s

  -
    modul: linehack
    local: true
    test:
      timeout: 30s

  -
    modul: ctemplate
    local: true
    test:
      timeout: 30s

  -
    modul: ctxout
    local: true
    test:
      timeout: 60s

  -
    modul: taskrun
    local: true
    test:
      timeout: 60s

  -
    modul: awaitgroup
    local: true
    version: "v0.4.0"
    test:
      timeout: 30s

  -
    modul: shellcmd
    local: true
    test:
      timeout: 30s

  -
    modul: ctxshell
    local: true
    test:
      timeout: 30s

  -
    modul: tasks
    local: true
    test:
      timeout: 30s
  
  - 
    modul: yaclint
    local: true
    test:
      timeout: 30s

  -
    modul: mimiclog
    local: true
    test:
      timeout: 30s

  -
    modul: manout
    local: false
    path: ${WS0_manout_root}

  -
    modul: outinject
    local: false
    path: ${WS0_outinject_root}
