FROM ubuntu:latest
ARG CTX_COLOROFF=true
ARG CTX_DISABLE_TABLE=true
COPY ./bin/contxt /usr/bin/
RUN chmod +x /usr/bin/contxt && \
    mkdir -p /etc/contxt
WORKDIR /etc/contxt

ENTRYPOINT ["/usr/bin/contxt"]
