config:
  sequencially: true
  coloroff: true
  variables: []
  imports:
    - filename.yaml
    - /test/filename.json
    - /check/filename.yml
task:
    - id: script
      variables: []
      stopreasons:
        onerror: true
        onoutcountLess: 0
        onoutcountMore: 0
        onoutContains:
          - context.json
          - fatal
      options:
        format: "log: %s\n"
        stickcursor: false
        colorcode: "97"
        bgcolorcode: "44"
        panelsize: 20
        displaycmd: true
        hideout: false
        maincmd: bash
        mainparams:
          - '-c'
      script:
        - echo 'hallo welt'
        - ls -ga
      listener:
          - trigger:
              onerror: true
              onoutcountLess: 0
              onoutcountMore: 0
              onoutContains:
                - context.json
                - fatal
            action:
              target: ""
              stopall: false
              script:
                - echo 'triggered by output parsing'