task:
    - id: script
      script:
        - echo 'hallo welt'
        - ls -ga
    - id: check
      script:
        - echo 'this is the check run'
        - find / -name '*jar'
      options:
        displaycmd: true
        hideout: false
      listener:
        - trigger:
            onoutContains:
              - maven
          action:
            script:
              - echo ' HIT --------------- HIT -------------- HIT'
    - id: test
      script:
        - "echo 'das ist run 2'"
      options:
        displaycmd: true