### This file is generated by using ./imports/go_test.tpl
### Any change you are doing here is overwritten while the next contxt build
### change go_test.tpl instead
name: looped-tests
on: push

jobs:
  ## testing if the build is running
  build:
    name: Test-In-Loops
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: ^1.18
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

## testing if we have some repeated testcases
    {{- if $.testcases.runner}}
    - name: Test-Loops
      run: {{ $.testcases.runner }} run test-loops
      
    {{- end }}
