### This file is generated by using ./imports/go_test.tpl
### Any change you are doing here is overwritten while the next contxt build
### change go_test.tpl instead
name: wip-test
on:
  push:
    branches:
      - "wip/**"

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: ^1.18
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Build contxt bin
      run: go build -ldflags "-X github.com/swaros/contxt/configure.minversion={{ $.release.version.minor }} -X github.com/swaros/contxt/configure.midversion={{ $.release.version.mid }} -X github.com/swaros/contxt/configure.mainversion={{ $.release.version.main }} -X github.com/swaros/contxt/configure.build=`date -u +.%Y%m%d.%H%M%S`" -o ./bin/contxt {{$.release.main}}

    - name: Test
      run: |
          ./bin/contxt run test-each
