### This file is generated by using ./imports/go_test.tpl
### Any change you are doing here is overwritten while the next contxt build
### change go_test.tpl instead
name: wip-test
on: push

jobs:
  ## testing if the build is running
  build:
    name: Test-Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: ^1.18
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

## test build
    {{- range $targetName, $targets := $.build.targets}}
    {{- if $targets.is_release}}
    - name: Build-{{ $targetName }}
      run: go build -ldflags "{{- range $k, $ldflag := $.build.preset.ldflags }} -X {{ $ldflag }} {{- end -}} {{- range $k, $ldflag := $targets.ldflags }} -X {{ $ldflag }} {{- end -}}" -o ./bin/{{ $targets.output }} {{ $targets.mainfile }}
    {{- end -}}
    {{- end }}

## tests
    {{- range $k, $test := $.module }}
    {{- if $test.local}}
    # test {{ $test.modul }}
    - name: Test-{{ $test.modul }}
      run: go test  -failfast ./module/{{ $test.modul }}/./...
    {{- end }}
    {{- end }}