name: wip-test
on:
  push:
    branches:
      - "wip/**"

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.18
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build contxt bin
      run: go build -ldflags "-X github.com/swaros/contxt/configure.minversion=`cat docs/minversion` -X github.com/swaros/contxt/configure.midversion=`cat docs/midversion` -X github.com/swaros/contxt/configure.mainversion=`cat docs/mainversion` -X github.com/swaros/contxt/configure.build=`date -u +.%Y%m%d.%H%M%S`" -i -o ./bin/contxt cmd/cmd-contxt/main.go

    - name: Test
      run: |
          ./bin/contxt run test-each

        
    
